language: php

sudo: true

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: deps=low
        - php: 5.6
          env: WITH_CRYPTO=true
        - php: 7.0
          env: deps=low
        - php: 7.0
          env: WITH_CRYPTO=true
        - php: 7.1
        - php: hhvm
        - php: hhvm
          env: deps=low
        - php: nightly

before_script:
    - composer self-update
    - sh -c 'if [ "$WITH_CRYPTO" != "" ]; then pecl install crypto-0.2.2; fi;'
    - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest ; fi
    - if [[ !$deps ]]; then composer install --no-interaction ; fi
    - mkdir -p build/logs
    - git clone --recursive https://github.com/bukka/php-crypto.git
    - cd php-crypto
    - phpize
    - ./configure
    - make
    - sudo make install
    - echo "extension = crypto.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - cd ..
    - git clone git://github.com/lt/php-curve25519-ext.git
    - cd php-curve25519-ext
    - phpize
    - ./configure
    - make
    - sudo make install
    - cd ..
    - echo "extension = curve25519.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - git clone git://github.com/encedo/php-ed25519-ext.git
    - cd php-ed25519-ext
    - phpize
    - ./configure
    - make
    - sudo make install
    - cd ..
    - echo "extension = ed25519.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
    - composer test-with-coverage

after_script:
    - vendor/bin/coveralls --no-interaction
    - php ./examples/Encrypt1.php
    - php ./examples/Encrypt2.php
    - php ./examples/Signature1.php
    - php ./examples/Signature2.php
    - php ./examples/Load1.php
    - php ./examples/Load2.php
    - php ./examples/Load3.php
    - php ./examples/Load4.php
